apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gen-ai-setup
  title: Generative AI Application Setup 0.78
  description: Create and register the Generative AI components on OpenShift
  tags:
    - ai
spec:
  owner: db-hackathon
  type: service
  parameters:
    - title: Application details
      required:
        - team_name
      properties:
        team_name:
          title: Name
          type: string
          maxLength: 20
          pattern: '^[a-z0-9-]*$'
        description:
          title: Description
          type: string
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: github.com
              enum:
                - github.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: db-hackathon
              enum:
                - db-hackathon
            token: 
              title: Github authentication token
              type: string
              description: A Github authentication token to be used to create repositories.
    - title: Provide information about the ArgoCD deployment
      required:
        - imageRepository
        - namespace
      properties:
        imageRepository:
          title: Select a registry
          type: string
          default: image-registry.openshift-image-registry.svc:5000
          enum:
            - image-registry.openshift-image-registry.svc:5000
          enumNames:
            - Internal OpenShift Registry
        namespace:
          title: Namespace
          type: string
          description: The namespace for deploying resources
  steps:
    - id: log
      name: Log parameters - 1
      action: debug:log
      input: 
        message: 'Parameters -> team_name : ${{ parameters.team_name }} description : ${{ parameters.description }}'

    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          team_name: ${{ parameters.team_name }}
          description: ${{ parameters.description }}
          owner: ${{ user.entity.metadata.name }}
          host: ${{ parameters.repo.host }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.team_name }}.git

    - id: manifestsTemplate
      name: Generating the Manifests Component
      action: fetch:template
      input:
        url: ./manifest/
        values:
          team_name: ${{parameters.team_name}}
          repo_owner: ${{ parameters.repo.owner }}
          repo_host: ${{ parameters.repo.host }}
          namespace: ${{ parameters.namespace }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{ parameters.team_name }}.git

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.team_name}}"
        repoVisibility: public
        defaultBranch: main
        token: '${{ parameters.repo.token }}'

    - id: log
      name: Log parameters - 2
      action: debug:log
      input: 
        message: 'Parameters -> repoContentsUrl : ${{ steps.publish.output.repoContentsUrl }}'
        listworkspace: true

    - id: log
      name: Log parameters - 2-a
      action: debug:log
      input: 
        message: 'Parameters -> owner : ${{ user.entity.metadata.name }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: log
      name: Log parameters - 3
      action: debug:log
      input: 
        message: 'Parameters -> catalogInfoUrl : ${{ steps.register.output.catalogInfoUrl }}'

    - id: log
      name: Log parameters - 4
      action: debug:log
      input: 
        message: 'Parameters -> remoteUrl : ${{ steps.publish.output.remoteUrl }}'
  
    - id: createArgocdResources
      name: Create the ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.team_name }}
        # Hardcoded value because this is kept as a secret on the server to allow forks to easily change the value
        argoInstance: argocd
        namespace: openshift-gitops
        repoUrl: ${{ steps.publish.output.remoteUrl }}
        labelValue: ${{ parameters.team_name }}
        path: 'argocd/'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    message-0: 'Parameters -> component_id : ${{ parameters.component_id }}'
    message-1: 'Parameters -> description  : ${{ parameters.description }}'