apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.team_name | dump }}
spec:
  destination:
    namespace: ${{ values.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest/base
    repoURL: ${{ parameters.repo_host }}/${{ parameters.repo_owner }}/${{parameters.team_name}}
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
