apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.team_name | dump }}
  # name: test
  namespace: openshift-gitops
spec:
  destination:
    namespace: ${{ values.namespace }}
    #namespace: app-test-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/
    repoURL: ${{ values.destination }}
    # repoURL: https://github.com/rh-uki-openshift-ssa/developer-hub-templates.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
