apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.team_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-selector: https://redhat-developer-hub-developer-hub.apps.cluster-l6kpl.sandbox1352.opentlc.com/openshift-gitops=${{values.team_name}}
    backstage.io/kubernetes-id: ${{values.team_name}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
    gitlab.com/project-slug: ${{values.destination}}
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}} 