apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: db-hackathon
  description: Red Hat Developer Hub admin team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: marrober
  description: Red Hat Developer Hub user team
spec:
  type: team
  profile:
    displayName: marrober
    picture: https://developers.redhat.com/sites/default/files/styles/article_feature/public/blog/2019/12/RedHatDeveloper_FeaturedImage.webp?itok=je5IHjLK
  parent: rhdh
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: marrober
spec:
  profile:
    # Intentional no displayName for testing
    email: marrober@redhat.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [marrober]